const WORKSPACE_MOBILE_BREAKPOINT = 769;
const WORKSPACE_CONTEXT_OVERLAY_BREAKPOINT = 1024;
const WORKSPACE_SIDEBAR_DEFAULT_WIDTH_PX = 288;
const WORKSPACE_SIDEBAR_MIN_WIDTH_PX = 224;
const WORKSPACE_SIDEBAR_MAX_WIDTH_PX = 384;
const WORKSPACE_CONTEXT_PANEL_DEFAULT_SIZE_PERCENT = 35.5;
const WORKSPACE_CONTEXT_PANEL_MIN_WIDTH_PX = 240;
const WORKSPACE_CONTEXT_PANEL_MAX_WIDTH_PX = 640;
const WORKSPACE_RAIL_HEIGHT_PX = 46;
const WORKSPACE_SURFACE_GUTTER_PX = 10;
const WORKSPACE_SURFACE_RADIUS_PX = 12;
const WORKSPACE_MOBILE_OVERLAY_MARGIN_PX = 40;

type WorkspacePanelPresentation = "mobile" | "overlay" | "inline";

function getWorkspacePanelPresentation(
  viewportWidth: number,
): WorkspacePanelPresentation {
  if (viewportWidth < WORKSPACE_MOBILE_BREAKPOINT) return "mobile";
  if (viewportWidth <= WORKSPACE_CONTEXT_OVERLAY_BREAKPOINT) return "overlay";
  return "inline";
}

export {
  getWorkspacePanelPresentation,
  WORKSPACE_CONTEXT_OVERLAY_BREAKPOINT,
  WORKSPACE_CONTEXT_PANEL_DEFAULT_SIZE_PERCENT,
  WORKSPACE_CONTEXT_PANEL_MAX_WIDTH_PX,
  WORKSPACE_CONTEXT_PANEL_MIN_WIDTH_PX,
  WORKSPACE_MOBILE_BREAKPOINT,
  WORKSPACE_MOBILE_OVERLAY_MARGIN_PX,
  WORKSPACE_RAIL_HEIGHT_PX,
  WORKSPACE_SIDEBAR_DEFAULT_WIDTH_PX,
  WORKSPACE_SIDEBAR_MAX_WIDTH_PX,
  WORKSPACE_SIDEBAR_MIN_WIDTH_PX,
  WORKSPACE_SURFACE_GUTTER_PX,
  WORKSPACE_SURFACE_RADIUS_PX,
  type WorkspacePanelPresentation,
};
